networks:
    internal:
        driver: bridge
        ipam:
            config:
                - subnet: 174.30.0.0/16

services:
    fake-phrasea:
        image: ${REGISTRY_NAMESPACE}fake-databox-api-nginx:${DOCKER_TAG}
        build:
            target: fake-databox-api-nginx
            context: ./
            dockerfile: ./databox/api/Dockerfile
        networks:
            - internal
#        volumes:
#            - ./:/srv/app
