networks:
    internal:
        driver: bridge
        ipam:
            config:
                - subnet: 174.30.0.0/16

services:
    fake-databox-api-php:
        image: ${REGISTRY_NAMESPACE}fake-databox-api-php:${DOCKER_TAG}
        build:
            target: fake-databox-api-php
            context: ./
            dockerfile: ./databox/api/Dockerfile
        networks:
            - internal
        volumes:
            - ./:/srv/app
