networks:
    internal:
        driver: bridge
        ipam:
            config:
                - subnet: 174.30.0.0/16

services:
    fake-phrasea:
        image: alchemyfr/fake-phrasea:${DOCKER_TAG}
        build:
            target: fake-phrasea
            context: ./
            dockerfile: ./databox/api/Dockerfile
        networks:
            - internal
#        volumes:
#            - ./:/srv/app
