name: export-doc

on:
  push:

env:
  REGISTRY_NAMESPACE: ghcr.io/${{ github.repository_owner }}/ps-
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  setup:
    name: setup
    if: "startsWith(github.ref, 'refs/tags/') || contains(github.event.head_commit.message, '[documentation]')"
    runs-on: ubuntu-latest
    steps:
      - name: get datetime
        run: |
          echo "DATETIME=$(date +%Y%m%d%H%I%S)" >> ${GITHUB_ENV}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start services
        run: docker compose up -d fake-databox-api-php --wait

      - name: install dependencies
        run: |
          docker compose exec -T fake-databox-api-php sh -c "cd databox/api && composer install"

      - name: export doc
        run: |
          docker compose exec -T fake-databox-api-php sh -c "php databox/api/application.php app:documentation:dump"

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Build and Push image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./databox/api/Dockerfile
          provenance: false
          push: true
          tags: |
            ${{ env.REGISTRY_NAMESPACE }}fake-databox-api-php:${{ github.ref_name }}

      - name: Trigger Workflow in documentation builder Repository
        run: |
          # Set the required variables
          repo_owner="alchemy-fr"
          repo_name="phrasea-documentation-builder"
          event_type="trigger-workflow"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\",\"client_payload\": {\"PHRASEA_REFNAME\": \"${{ github.ref_name }}\", \"PHRASEA_REFTYPE\": \"${{ github.ref_type }}\", \"PHRASEA_DATETIME\": \"${{ env.DATETIME }}\"}}"
