name: export-doc

on:
  release:
    types: [ created ]
env:
  REGISTRY_NAMESPACE: ghcr.io/${{ github.repository_owner }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: Dump vars
        run: |
          echo "===== on_release.yaml ====="
          echo "github.ref = ${{ github.ref }}"
          echo "github.sha = ${{ github.sha }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.repository = ${{ github.repository }}"
          echo "github.event.release.tag_name = ${{ github.event.release.tag_name }}"
          echo "env.REGISTRY = ${{ env.REGISTRY }}"
          echo "env.REGISTRY_NAMESPACE = ${{ env.REGISTRY_NAMESPACE }}"
